json:
  travis_build_environment:
    use_tmpfs_for_builds: false
    home: /Users/travis
    group: staff
  rvm:
    default: "1.9.3"
    rubies:
      - name: "1.9.3"
    gems:
      - bundler
      - rake
      - cocoapods
recipes:
  - homebrew
  - travis_build_environment::osx
  - rvm::multi
  - cocoapods
