memory: 1536
json:
  rvm:
    rubies:
    - name: 1.8.7
    - name: 1.9.2-head
    - name: 1.9.3
    - name: jruby
    - name: rbx-head
      arguments: --branch 2.0.testing
      using: 1.8.7
    default:
      - ruby-1.8.7
    gems:
      - bundler
      - rake
      - chef
    aliases:
      1.9.2: 1.9.2-head
  travis_build_environment:
    use_tmpfs_for_builds: true
recipes:
  - travis_build_environment
  - rvm
  - rvm::multi
  - mysql::server_on_ramfs
  - postgresql::server_on_ramfs
