json:
  nodejs:
    versions:
      - 0.6.21
      - 0.8.24
      - 0.9.12
      - 0.10.18
      - 0.11.7
    aliases:
      0.6.21: 0.6
      0.8.24: 0.8
      0.9.12: 0.9
      0.10.10: 0.10
      0.11.7: 0.11
    default: 0.10.18
recipes:
  - nodejs::multi
  - sweeper
