json:
  nodejs:
    versions:
      - 0.6.21
      - 0.8.22
      - 0.9.12
      - 0.10.5
      - 0.11.1
    aliases:
      0.6.21: 0.6
      0.8.21: 0.8
      0.9.12: 0.9
      0.10.5: 0.10
      0.11.1: 0.11
      0.11.1: node-head
    default: 0.8.22
recipes:
  - nodejs::multi
  - sweeper
